name: Manual docker execution
on: 
  workflow_dispatch:
    inputs:
      text_to_be_geolocate:
        description: example text to derive location from
        default: 'Die Karl-Liebknecht-Straße (umgangssprachlich Karli) ist eine bedeutende Straße in Leipzig, die sich vom südlichen Stadtzentrum nach Süden zieht. Die etwa 2,5 Kilometer lange Straße erstreckt sich als Fortsetzung des Peterssteinwegs vom Abzweig der Emilienstraße im Stadtgebiet Zentrum-Süd über die Südvorstadt bis zum Connewitzer Kreuz in Connewitz. Die Karl-Liebknecht-Straße entstand während des Baubooms Ende des 19. Jahrhunderts beziehungsweise um 1880. Davor befand sich hier ein weniger stark befestigter Weg, der dem Verlauf der heutigen Kochstraße folgte. Der Weg verband die Leipziger Innenstadt mit Alt-Connewitz. Der nördliche Straßenabschnitt bis zum Südplatz bestand schon im Mittelalter und war Teil der Via Imperii. Bis etwa Mitte des 19. Jahrhunderts hieß dieser Abschnitt Connewitzer Chaussee[1] und von 1839 mit dem Ausbau der Südvorstadt bis 1933 hieß er Zeitzer Straße.[2] Bis 1856 stand an seinem südlichen Ende das „äußere Peterstor“ („Zeitzer Tor“). Der sich anschließende Straßenabschnitt stadtauswärts ab Schenkendorfstraße[1] hieß von 1874 bis 1933 Südstraße.'
        required: true

jobs:
  localize:
    name: localize
    runs-on: ubuntu-latest
    environment: scrape_papers_envs
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: DockerExtractor
      run: docker-compose -f "docker/location-extractor.yml" up -d --build
    - name: Wait on
      uses: iFaxity/wait-on-action@v1.1.0
      with:
        resource: http://localhost:8081      
        timeout: 30000
    - name: Extract
      run: |
        extracted = $(curl --location 'http://localhost:8081/api/address/extract' --header 'Content-Type: text/plain' --data '${{ github.event.inputs.text_to_be_geolocate }}')
        echo "extracted=$extracted" >> $GITHUB_OUTPUT 
    - name: "echo location"
      run: |
        echo "Output [${{steps.Extract.outputs.extracted}}]"
    - name: DockerLocator
      run: docker-compose -f "docker/location-locator.yml" up -d --build
    - name: Wait on
      uses: iFaxity/wait-on-action@v1.1.0
      with:
        resource: http://localhost:8082 
        timeout: 30000
    - name: Locate
      run: |
        located = $(curl --location 'http://localhost:8082/api/locations/locate?location=S%C3%BCdplatz')
        echo "located=$located" >> $GITHUB_OUTPUT 
    - name: "echo coords"
      run: |
        echo "Output [${{steps.Locate.outputs.located}}]"